### PR TITLE
Fix "Devices and IoT" string typo

### LINKED ISSUE #1224: Typo in the "Devices and IOT" string
The "Devices and IOT" string contains a small typo: "IOT" should be "IoT" (lowercase "**o**").

### PR DESCRIPTION
**Pull request by AsciiWolf**
IOT -> IoT

Fixes #1224.

### CODE REVIEW

**Comment by AsciiWolf** [comment]
My CLA signature should now be valid. Feel free to re-run the cla-check.

**Comment by Feichtmeier** [comment]
@AsciiWolf please use weblate for translation

**Comment by Feichtmeier** [comment]
@AsciiWolf please use weblate for translation ah.... I actually don't know if the original English file can be edited via weblate

**Comment by AsciiWolf** [comment]
> Ahhh I actually don't know if the original English file can be edited via weblate

Thanks! It looks like it actually can be edited via Weblate and I have edited it there. :-)

**Pull request closed without merging**
